### ISSUE TITLE
Example Error

### ISSUE THREAD

**Issue by jimmyjin** [intentmedia/admm#9]
Hi,

I followed the Readme steps and got the following error. Would you please check for me? Thx.

admm]$ hadoop jar build/libs/admm.jar com/intentmedia/admm/AdmmOptimizerDriver
Exception in thread "main" java.lang.NoClassDefFoundError: org/kohsuke/args4j/CmdLineException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:227)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:148)
Caused by: java.lang.ClassNotFoundException: org.kohsuke.args4j.CmdLineException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

**Comment by orikremer** [comment]
Hi @jimmyjin,

This project is no longer supported, and will soon be removed. 
Sorry for the inconvenience.
